version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-api-docker
    ports:
      - "4566:4566"
    environment:
      - SERVICES= dynamodb
      - DATA_DIR=/tmp/localstack/data

  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "shakeel.mohammed1/client"
    ports:
      - "3000:3000"
    links:
      - "backend:be"

  backend:
    build:
      context: ./rest-api-service
      dockerfile: ./Dockerfile
    depends_on:
      - localstack
    image: "shakeel.mohammed1/rest-api-service"
    ports:
      - "3001:3001"
    environment:
      STAGE: 'local'
      AWS_ENDPOINT: 'http://localstack:4566'
      REGION: 'ap-southeast-2'